version: '3'
services:
  mongodb:
    container_name: mongo
    image: mongo:6.0.4
    volumes:
      - /mnt/cache/appdat/mongodb_data:/data/db
    restart: "unless-stopped"
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=EST5EDT
    networks:
      - graylog  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    volumes:
      - /mnt/cache/appdata/es_data:/usr/share/elasticsearch/data
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: "unless-stopped"
    networks:
      - graylog
  graylog:
    container_name: graylog
    image: graylog/graylog:6.1.4
    volumes:
      - /mnt/cache/appdata/graylog_data:/usr/share/graylog/data
    environment:
      # Change these to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      - ROOT_TIMEZONE=EST5EDT
      - GRAYLOG_TIMEZONE=EST5EDT
      # CHANGE ME (must be at least 16 characters)! This is not your password, this is meant for salting the password below.
      - GRAYLOG_PASSWORD_SECRET=ZDcwMzQ3NTE4ZTIwM
      # Username is "admin"
      # Password is "admin", change this to your own hashed password. 'echo -n "password" | sha256sum' 
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.2.238:9001/
      
    networks:
      - graylog
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9001:9000
      # Syslog UDP
      - 1514:1514/udp
      # Syslog TCP Optional
      #- 1514:1514
    restart: "unless-stopped"
  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    ports:
      - '8086:8086'
    volumes:
      - /mnt/cache/appdata/influxdb2_data:/var/lib/influxdb2
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
    restart: "unless-stopped"
    networks:
      - graylog
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.10
    ports:
      - '3000:3000'
    volumes:
      - /mnt/cache/appdata/grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      # Change this to your time zone, valid time zones can be found here: https://www.joda.org/joda-time/timezones.html
      - TZ=CST6CDT
      # Change these
      - GF_SECURITY_ADMIN_USER=opnsense
      - GF_SECURITY_ADMIN_PASSWORD=opnsense
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
    restart: "unless-stopped"
    networks:
      - graylog
networks:
  graylog:
    driver: bridge
#volumes:
  #grafana_data:
  #influxdb2_data:
  #graylog_data:
  #es_data:
  #mongodb_data:
